### ISSUE TITLE
Include raster time-series as part of this tutorial?

### ISSUE THREAD

**Issue by loicdtx** [GeoScripting-WUR/IntroToRaster#2]
Considering that there will be an entire day dedicated to this tutorial, it seems reasonable to add a section on raster time-series here + a time-series exercise in addition to the compositing exercise. What do you think Jan?

**Comment by janverbesselt** [comment]
Loïc, I spoke about it with Ben and the time series part would fit in the advanced raster section (i.e. the old lessons 6-7. ok?

**Comment by loicdtx** [comment]
I think the lessons would be better balanced if time-series would be included as part of the intro to raster (this tutorial) rather than in last year's Lesson 6, which already has quite a lot of content.
