### ISSUE TITLE
System overview schematic is somewhat misleading

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/IntroToRaster#5]
The system overview schematic that's at the top of the main lesson is very nice and informative, however, it is also a bit misleading:
![Current image](https://raw.githubusercontent.com/GeoScripting-WUR/IntroToRaster/gh-pages/figs/system_overview_2.png)

Specifically, git and SVN are not IDEs. They would probably be at the engine level. Also, SVN wasn't mentioned much during the course altogether (for a good reason, too ;) ).

Similarly, `raster`, `sp`, `maptools` and such packages are ones that are most likely to interact with `rgdal` and `rgeos`, using those from R directly is often times not needed. So I'd either combine the R and the package bubble together, or put the package bubble under R, or have all four interconnected with arrows.

If talking about spatial data, then also the "Data" cloud should most likely be connected not directly to R (since base R can only read CSVs), but rather to the library layer.

Lastly, the text below the schematic says "In a previous lecture you saw the overall system architecture", which is also a bit misleading, since the particular image had not appeared in previous lesson pages.

As a side note, it looks like the schematic was made using LibreOffice Draw; it can export vector images too, so if the GitHub rendering engine can display those (it should be able to display SVGs), it might be a better option. In addition, storing the original files somewhere would be useful for editing them later on.

**Comment by janverbesselt** [comment]
excellent comments that all make sense. Loïc is the author of this nice graph. maybe he can share the  the original files so that we can further improve these. If not, we can do a quick redrawing in an "open" format so that we can collaborate on editing this figure. Feel free to give the new drawing a try if you have time.

**Comment by GreatEmerald** [comment]
All right, I remade it, here's how it looks:

![Remade image](http://geoscripting-wur.github.io/IntroToRaster/figs/geoscripting-system-overview.svg)

I commited it into `figs`, in both editable ODG format and web-optimised SVG format. If that looks good, it can be put into `index.Rmd`.

**Comment by janverbesselt** [comment]
Looks good. What is the advantage of R KWard versus Rstudio? The can maybe explained in the index.rmd or if there is not real advantage with could keep this figure more simple by leaving out RKWard and refer to the following list of other editors; https://rkward.kde.org/General_FAQ#Are_there_other_R_GUIs.3F

**Comment by GreatEmerald** [comment]
My idea with that bubble was just to show that there are more than just one R IDE. It could indeed be noted in the text instead, and the bubble could either say something like "RStudio, ..." or have the RStudio logo in it (though it's just the letter R in a bubble, which can be confused with the logo of R itself).

As for what's the advantage of RKWard: it's a natively compiled application that is packaged everywhere, so one can easily install it just with `apt-get` or so, whereas RStudio requires one to download it from their website or use a ppa, which is more complicated and risk-prone (OSGeo Live has it preinstalled, but it's an exception rather than the rule, and it doesn't keep track of updates to it either), and RKWard is also more user-friendly for beginners as it is more dialog-based, like other statistical programs (the menu allows things like drawing distributions, doing statistical tests, making various plots in the GUI instead of writing by hand, but also shows the text equivalent of what will be run so it can be copy-pasted into a script), as well as includes a graphical data frame editor. It doesn't have integration with git, though, which is why the line to git is dashed (but I'd say that's a good thing, as Git GUI is a better solution anyway). Its R package manager natively compiles packages rather than using prebuilt binaries like RStudio, which makes it easy to update R versions and makes packages faster (but it also takes longer to install them, as it needs to compile them, and sometimes requires dependencies like gfortran, libproj, etc.).

**Comment by janverbesselt** [comment]
ok nice and interesting; feel free to include RKWard, example.

**Comment by GreatEmerald** [comment]
Done. I added a short note on RKWard (this lesson is pretty basic, so the students should have enough time to look at it if they wish).

I tried knitting this myself on the VM, but it creates .md files instead of .html. Here's the result: http://geoscripting-wur.github.io/IntroToRaster/test.html It's kind of working, but it's not as nice as the HTML versions.
